package com.recallbot.ai.citation;

import com.recallbot.search.dto.SearchHit;
import org.springframework.stereotype.Component;

import java.util.Collections;
import java.util.List;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/**
 * Validates message citations returned by the LLM against actually retrieved search hits.
 * Strips fabricated or hallucinated citations to prevent misleading references.
 */
@Component
public class CitationValidator {

    private static final Pattern CITATION_PATTERN = Pattern.compile("\\[(?:Msg|Message)\\s*(?:#|:)?\\s*(\\d+)\\]", Pattern.CASE_INSENSITIVE);

    /**
     * Sanitizes the answer text by stripping citations referencing message IDs that were not retrieved.
     *
     * @param rawAnswer the raw response generated by the LLM
     * @param hits      the list of search hits provided to the prompt
     * @return the sanitized answer with only verified citations preserved
     */
    public String validateAndSanitize(String rawAnswer, List<SearchHit> hits) {
        if (rawAnswer == null || rawAnswer.isBlank()) {
            return rawAnswer;
        }

        Set<Long> validMessageIds = (hits == null || hits.isEmpty())
                ? Collections.emptySet()
                : hits.stream()
                .map(SearchHit::telegramMessageId)
                .filter(id -> id != null)
                .collect(Collectors.toSet());

        Matcher matcher = CITATION_PATTERN.matcher(rawAnswer);
        StringBuilder sb = new StringBuilder();

        while (matcher.find()) {
            String idStr = matcher.group(1);
            try {
                long messageId = Long.parseLong(idStr);
                if (validMessageIds.contains(messageId)) {
                    // Valid citation: keep standardized format [Msg #ID]
                    matcher.appendReplacement(sb, Matcher.quoteReplacement("[Msg #" + messageId + "]"));
                } else {
                    // Hallucinated citation: strip it out
                    matcher.appendReplacement(sb, "");
                }
            } catch (NumberFormatException e) {
                matcher.appendReplacement(sb, "");
            }
        }
        matcher.appendTail(sb);

        // Clean up whitespace before punctuation (including Indic danda characters) and redundant double spaces left from stripped citations
        return sb.toString()
                .replaceAll(" +([.,!?;:|॥।])", "$1")
                .replaceAll(" +", " ")
                .trim();
    }
}
